[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "@netlify/plugin-lighthouse@v6"
[build]
  command = "npm run build"
  publish = ".next"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
