[build]
base = "app"
command = "yarn build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[redirects]]
from = "/*"
to = "/blog/:splat"
status = 404

[[redirects]]
from = "/blog/:slug/*"
to = "/blog/:slug"
